Add origins:scoreboard and origins:command conditions
apace100/origins-fabric pull request #148
Opened 2021-02-24 23:06 UTC by xMGZx

Ideas for:
+ Added origins:scoreboard and origins:command conditions
+ Set the default permission level to 4
+ Added != comparison (as it is useful in the case of origins:scoreboard)

2021-02-25 00:16 UTC, apace100 commented
Could you post examples of how one would use these conditions? :)

2021-02-25 02:54 UTC, xMGZx commented
Well the idea is to more strongly connect functions and powers together, and to massively increase the potential of conditions overall.

First, the scoreboard condition. Let's say you have a power defined with this condition:
```json
{
    "condition": "origins:scoreboard",
    "objective": "obj",
    "comparison": ">",
    "compare_to": 3
}
```
and this scoreboard objective:
`/scoreboard objectives add obj dummy`

this condition would only be true if the player's scoreboard objective was greater than 3, which can be modified in many different ways (unlike resources, which can only be modified in one way, and are untouchable by functions):
`/scoreboard players set @s obj 4`
`/scoreboard players add @s obj 4`
`/scoreboard players remove @s obj 4`
`/scoreboard players operation @s obj <operation> <Player> <otherObjective>`

If the player does _not_ have the scoreboard objective (that is, if `/scoreboard objectives add obj dummy` has been run and none of the above commands were run), this condition would always return false (even if != is run). You can then use the != comparison in combination with the == comparison to test if the player does not have this objective set (for example if a player has newly joined a world or had their objectives reset).

Second, the command condition. It can do everything the scoreboard condition can do (though having the scoreboard objective is better because it can run instantly) and more. Every command in minecraft returns an integer; 1 on success and 0 on failure. Some commands even return numerical values. Take for example the [`/execute if`](https://minecraft.gamepedia.com/Commands/execute#Condition_subcommands) subcommand. You can use this both to test for entites, blocks, storages, custom predicates and also _count_ how many things exist in the world. Another example is the `/clear @s <item> 0` command, which counts how many items a player has.

Take for example this command:
`/execute if entity @e[distance=..3,type=creeper,nbt={powered:1b}]`
This returns the number of supercharged creepers within a three block radius of the player. So lets define a condition like this:

```json
{
    "condition": "origins:command",
    "command": "execute if entity @e[distance=..3,type=creeper,nbt={powered:1b}]",
    "comparison": ">",
    "compare_to": 1
}
```

This condition would only be true if there is more than 1 supercharged creeper near the player.

Another thing to remember is that these _should_ support modded commands too. Imagine using something like the `/script` command from [scarpet](https://github.com/gnembon/scarpet), which can do almost anything. The power of these conditions ultimately rests upon the already in-place powerful minecraft command system; this one condition introduces so many other conditions (including the objective one) it's crazy.

2021-02-25 06:52 UTC, apace100 requested changes

2021-02-25 06:52 UTC, apace100 commented on src/main/java/io/github/apace100/origins/power/factory/condition/PlayerConditions.java
> +                    return ((Comparison)data.get("comparison")).compare(output, data.getDouble("compare_to"));
The "compare_to" parameter is an integer, so this needs to be changed to `data.getInt("compare_to")`

2021-02-25 06:52 UTC, apace100 commented on src/main/java/io/github/apace100/origins/util/Comparison.java
> +    NOT_EQUAL("!=", (a, b) -> a != b);
Not equal comparison should use `!a.equals(b)` because they are number objects, not primitives.

2021-02-26 08:37 UTC, apace100 approved these changes

2021-03-01 12:43 UTC, apace100 commented
Merged this manually into `feature` branch: https://github.com/apace100/origins-fabric/commit/62150ce54835a6fc1e5151e87352890d3316cae0

2021-03-01 12:43 UTC, closed without merging